version: '3.1'

services:

  gptbot:
    container_name: chimera-gpt-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      MODE: DOCKER
      DB_HOST: mongo
